package stakingrequests

import (
	"bytes"
	"encoding/hex"
	"math"
	"testing"

	ssz "github.com/prysmaticlabs/fastssz"
	"github.com/theQRL/go-qrl/common"
)

// Frozen nonzero vectors were generated by the exploratory Python specification.
// Compare their SSZ root independently with the client's native fastssz library.
func TestSyntheticVectorAndNativeSSZ(t *testing.T) {
	publicKey := make([]byte, PublicKeyBytes)
	for i := range publicKey {
		publicKey[i] = byte(i % 251)
	}
	root, err := PublicKeyRoot(publicKey)
	if err != nil {
		t.Fatal(err)
	}
	wantRoot := common.HexToHash("d808c9d029dac6b8c80e02de706124b1183e60dfeed7899bc6d3a66bbff37986")
	if root != wantRoot {
		t.Fatalf("key root: got %x, want %x", root, wantRoot)
	}
	hasher := ssz.NewHasher()
	hasher.PutBytes(publicKey)
	nativeRoot, err := hasher.HashRoot()
	if err != nil || common.Hash(nativeRoot) != wantRoot {
		t.Fatalf("native SSZ root: %x, error %v", nativeRoot, err)
	}
	request := Request{ValidatorIndex: 0x0102030405060708, PublicKeyRoot: root}
	for i := range request.Source {
		request.Source[i] = byte(i)
	}
	wantRecord := "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f0807060504030201d808c9d029dac6b8c80e02de706124b1183e60dfeed7899bc6d3a66bbff37986"
	if hex.EncodeToString(request.Encode()) != wantRecord {
		t.Fatal("record differs from frozen vector")
	}
	if hex.EncodeToString(request.Submission()) != "0102030405060708d808c9d029dac6b8c80e02de706124b1183e60dfeed7899bc6d3a66bbff37986" {
		t.Fatal("submission differs from frozen vector")
	}
	hash, err := HashGroups(Groups([]Request{request}))
	if err != nil || hash != common.HexToHash("e1de7e13603035fc3e626ced65ffbf9366deb103096a0d5d271e14454c4233c5") {
		t.Fatalf("request hash: %x, error %v", hash, err)
	}
	decoded, err := Decode(request.Encode())
	if err != nil || decoded != request {
		t.Fatalf("decode: %#v, error %v", decoded, err)
	}
}

func TestEncodingBoundaries(t *testing.T) {
	for _, index := range []uint64{0, 1, math.MaxUint64} {
		request := Request{Source: common.BytesToAddress(bytes.Repeat([]byte{0xa5}, 64)), ValidatorIndex: index}
		decoded, err := Decode(request.Encode())
		if err != nil || decoded != request {
			t.Fatalf("index %d: %v", index, err)
		}
	}
	for _, size := range []int{0, 103, 105, 2664} {
		if _, err := Decode(make([]byte, size)); err == nil {
			t.Errorf("accepted record width %d", size)
		}
	}
	for _, size := range []int{0, 48, 2591, 2593} {
		if _, err := PublicKeyRoot(make([]byte, size)); err == nil {
			t.Errorf("accepted key width %d", size)
		}
	}
}

func TestCanonicalGroupsAndCommitment(t *testing.T) {
	empty, err := HashGroups(nil)
	if err != nil || empty != common.HexToHash("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855") {
		t.Fatal("incorrect empty commitment")
	}
	requests := []Request{{ValidatorIndex: 1}, {ValidatorIndex: 2}}
	groups := Groups(requests)
	hash, _ := HashGroups(groups)
	if err := ValidateCommitment(requests, groups, hash, MaxPerBlock); err != nil {
		t.Fatal(err)
	}
	for _, malformed := range [][][]byte{
		{{}}, {{Type}}, {{2, 1}}, {groups[0], groups[0]},
		{groups[0][:len(groups[0])-1]}, {append(append([]byte{}, groups[0]...), requests[0].Encode()...)},
	} {
		if _, err := ValidateGroups(malformed, MaxPerBlock); err == nil {
			t.Fatalf("accepted malformed groups: %x", malformed)
		}
	}
	for _, malformed := range [][][]byte{{{}}, {{Type}}, {{1, 1}, {1, 2}}, {{2, 1}, {1, 1}}} {
		if _, err := HashGroups(malformed); err == nil {
			t.Fatal("accepted noncanonical envelope")
		}
	}
	for _, changed := range [][]Request{nil, requests[:1], {requests[1], requests[0]}, {{ValidatorIndex: 1, Source: common.BytesToAddress([]byte{1})}, requests[1]}} {
		supplied := Groups(changed)
		selfConsistentHash, _ := HashGroups(supplied)
		if err := ValidateCommitment(requests, supplied, selfConsistentHash, MaxPerBlock); err == nil {
			t.Fatal("accepted metadata differing from executed requests")
		}
	}
	if err := ValidateCommitment(requests, groups, empty, MaxPerBlock); err == nil {
		t.Fatal("accepted wrong commitment")
	}
	if _, err := ValidateGroups(nil, 0); err == nil {
		t.Fatal("accepted zero bound")
	}
}
